version: 2.1

jobs:
  check-pl:
    docker:
      - image: cimg/python:3.11   # python 3.11 on ubuntu
    steps:
      - checkout

      - run:
          name: Upgrade pip
          command: |
            python -m pip install --upgrade pip

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Install Playwright browsers
          command: |
            playwright install --with-deps

      - run:
          name: Run PL game checker
          command: |
            python check_no_pl_game.py

workflows:
  check-pl-schedule:
    triggers:
      - schedule:
          cron: "*/15 * * * *"
          filters:
            branches:
              only:
                - main
          # explicitly set time zone to UTC
          type: time
    jobs:
      - check-pl