version: 2.1

jobs:
  check-pl:
    docker:
      - image: cimg/python:3.11   # python 3.11 on ubuntu
    steps:
      - checkout

      - run:
          name: Upgrade pip
          command: |
            python -m pip install --upgrade pip

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Install Playwright browsers
          command: |
            playwright install --with-deps

      - run:
          name: Run PL game checker
          command: |
            python check_no_pl_game.py
          environment:
            TWITTER_API_KEY: << pipeline.parameters.TWITTER_API_KEY >>
            TWITTER_API_SECRET: << pipeline.parameters.TWITTER_API_SECRET >>
            TWITTER_ACCESS_TOKEN: << pipeline.parameters.TWITTER_ACCESS_TOKEN >>
            TWITTER_ACCESS_SECRET: << pipeline.parameters.TWITTER_ACCESS_SECRET >>
            TELEGRAM_BOT_TOKEN: << pipeline.parameters.TELEGRAM_BOT_TOKEN >>
            TELEGRAM_CHAT_ID: << pipeline.parameters.TELEGRAM_CHAT_ID >>

workflows:
  scheduled:
    triggers:
      - schedule:
          # CircleCI uses standard cron syntax (UTC)
          cron: "*/15 * * * *"    # every 15 minutes
          filters:
            branches:
              only: main
    jobs:
      - check-pl
